// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.Infrastructure.EntityFramework;

#nullable disable

namespace ProfileService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250202165026_AddAchievementsAndFilesAchievementTables")]
    partial class AddAchievementsAndFilesAchievementTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileInfoId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.FileAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("FilesAchievement");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.LevelTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LevelsTraining");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.ProfileInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.TypeSportEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypesSportEquipment");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.ClientProfileInfo", b =>
                {
                    b.HasBaseType("ProfileService.Domain.Entities.ProfileInfo");

                    b.Property<Guid>("OwnerProfileInfoId")
                        .HasColumnType("uuid");

                    b.ToTable("ClientProfiles", (string)null);
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.InstructorProfileInfo", b =>
                {
                    b.HasBaseType("ProfileService.Domain.Entities.ProfileInfo");

                    b.Property<DateTime?>("DateDismissal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExperienceBeforeHiring")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PositionId")
                        .HasColumnType("integer");

                    b.HasIndex("PositionId");

                    b.ToTable("InstructorProfiles", (string)null);
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("ProfileService.Domain.Entities.ProfileInfo", "ProfileInfo")
                        .WithMany("Achievements")
                        .HasForeignKey("ProfileInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileInfo");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.FileAchievement", b =>
                {
                    b.HasOne("ProfileService.Domain.Entities.Achievement", "Achievement")
                        .WithMany("FilesAchievement")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.ClientProfileInfo", b =>
                {
                    b.HasOne("ProfileService.Domain.Entities.ProfileInfo", null)
                        .WithOne()
                        .HasForeignKey("ProfileService.Domain.Entities.ClientProfileInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.InstructorProfileInfo", b =>
                {
                    b.HasOne("ProfileService.Domain.Entities.ProfileInfo", null)
                        .WithOne()
                        .HasForeignKey("ProfileService.Domain.Entities.InstructorProfileInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfileService.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("FilesAchievement");
                });

            modelBuilder.Entity("ProfileService.Domain.Entities.ProfileInfo", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
